openapi: 3.0.0
info:
  title: Bank Accounts Microservice
  description: API para gestionar productos pasivos (cuentas bancarias).
  version: 1.0.0
servers:
  - url: https:///localhost:8080
    description: Servidor principal

paths:
  /accounts:
    post:
      summary: Crear una nueva cuenta bancaria
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountBase'
      responses:
        '201':
          description: Cuenta creada exitosamente
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '400':
          $ref: '#/components/responses/BadRequest'
        '422':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /accounts/{accountId}:
    get:
      summary: Obtener detalles de una cuenta específica
      operationId: getAccountById
      parameters:
        - name: accountId
          in: path
          required: true
          description: ID de la cuenta bancaria
          schema:
            type: string
      responses:
        '200':
          description: Detalles de la cuenta bancaria
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      summary: Actualizar una cuenta bancaria
      operationId: updateAccount
      parameters:
        - name: accountId
          in: path
          required: true
          description: ID de la cuenta bancaria
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountBase'
      responses:
        '200':
          description: Cuenta actualizada exitosamente
          content:
              application/json:
                schema:
                  type: object
                  additionalProperties: true
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      summary: Eliminar una cuenta bancaria
      operationId: deleteAccount
      parameters:
        - name: accountId
          in: path
          required: true
          description: ID de la cuenta bancaria
          schema:
            type: string
      responses:
        '200':
          description: Cuenta eliminada exitosamente
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true

        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /accounts/all:
      get:
        summary: Obtener todas las cuentas bancarias
        operationId: getAllAccounts
        responses:
          '200':
            description: Lista de cuentas bancarias
            content:
                application/json:
                  schema:
                    type: object
                    additionalProperties: true

          '500':
            $ref: '#/components/responses/InternalServerError'

  /accounts/transactions:
    post:
      summary: Registrar una nueva transacción en la cuenta
      operationId: createTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          description: Transacción registrada exitosamente
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true


        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalServerError'

    get:
      summary: Obtener todas las transacciones
      operationId: getAllTransactions
      responses:
        '200':
          description: Historial completo de transacciones
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true

        '500':
          $ref: '#/components/responses/InternalServerError'

  /accounts/{accountId}/transactions:
    get:
      summary: Obtener transacciones por ID de cuenta
      operationId: getTransactionsByAccountId
      parameters:
        - name: accountId
          in: path
          required: true
          description: ID de la cuenta bancaria
          schema:
            type: string
      responses:
        '200':
          description: Transacciones de la cuenta especificada
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'


components:
  schemas:
    Person:
      type: object
      required:
        - dni
        - name
      properties:
        dni:
          type: string
          pattern: ^[0-9]{8,12}$
          example: "12345678"
        name:
          type: string
          minLength: 2
          maxLength: 100
          example: "Juan Pérez"


    AccountType:
      type: string
      enum:
        - savings
        - checking
        - fixed-term
      example: "savings"

    CustomerType:
        type: string
        enum:
          - personal
          - business
        example: "personal"

    AccountBase:
      type: object
      required:
        - accountType
        - customerId
        - customerType
      properties:
        accountId:
          type: string
        accountType:
          $ref: '#/components/schemas/AccountType'
        balance:
          type: number
          minimum: 0
          example: 1500.75
        allowedDayOfMonth:
          type: string
        customerId:
          type: string
        customerType:
          $ref: '#/components/schemas/CustomerType'
        owners:
          type: array
          items:
            $ref: '#/components/schemas/Person'
        authorizedSigners:
          type: array
          items:
            $ref: '#/components/schemas/Person'
        maintenanceFee:
          type: number
          description: Comisión de mantenimiento
        monthlyMovementLimit:
          type: integer
          description: Límite de movimientos mensuales

    CheckingAccount:
      allOf:
        - $ref: '#/components/schemas/AccountBase'
        - type: object
          required:
            - maintenanceFee

    SavingsAccount:
      allOf:
        - $ref: '#/components/schemas/AccountBase'
        - type: object
          required:
            - monthlyMovementLimit

    FixedTermAccount:
      allOf:
        - $ref: '#/components/schemas/AccountBase'
        - type: object
          required:
            - allowedDayOfMonth

    Transaction:
      type: object
      required:
        - type
        - amount
        - accountId
      properties:
        transactionId:
          type: string
        date:
          type: string
          format: date-time
        type:
          type: string
          enum:
            - deposit
            - withdrawal
          example: "deposit"
        amount:
          type: number
        accountId:
          type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: "VALIDATION_ERROR"
        message:
          type: string
          example: "El campo accountType es requerido"
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

  responses:
    BadRequest:
      description: Solicitud incorrecta
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "BAD_REQUEST"
            message: "Parámetros de solicitud inválidos"

    NotFound:
      description: Recurso no encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "NOT_FOUND"
            message: "Cuenta no encontrada"

    ValidationError:
      description: Error de validación
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "VALIDATION_ERROR"
            message: "Error de validación en los datos de entrada"
            details:
              - field: "initialDeposit"
                message: "El depósito inicial debe ser mayor que cero"
              - field: "accountType"
                message: "El tipo de cuenta debe ser uno de: savings, checking, fixed-term"

    InternalServerError:
      description: Error interno del servidor
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: "INTERNAL_SERVER_ERROR"
            message: "Ha ocurrido un error interno. Intente nuevamente más tarde."